title: Capturing and Crafting Visual Stories
description: I deliver end-to-end media services spanning portrait photography, event videography, drone aerials, and post-production. Here are a few examples of the work that reflects my creative style and visual storytelling approach.
links:
  - label: "Let's talk"
    to: https://instagram.com/prograker/
  - label: "Email me"
    to: mailto:business@aghiljose.com
    color: "secondary"
